### ISSUE TITLE
"Enable failed: failed to execute command: command terminated with exit status=2"

### ISSUE THREAD

**Issue by yoshioterada** [haroldwongms/openshift-enterprise#1]
After executed the following four commands, I tried to create the OpenShift Container Platformon on Azure by using Azure Portal Screen(push the "Deploy to Azure" button).

$ azure group create 'OpenShiftRSG' 'Japan West'
$ azure keyvault create --vault-name 'OSKeyVault' --resource-group 'OpenShiftRSG' --location 'Japan West'
$ azure keyvault secret set -u 'OSKeyVault' -s 'MySecret' --file ~/.ssh/openshift-azure_rsa
$ azure keyvault set-policy -u 'OSKeyVault' --enabled-for-template-deployment true

Then following error occur and failed to install the OpenShift on Azure.
(I could login to the master node from outside of the network.)

[*****_@clus1master ~]$ uname -a
Linux clus1master 3.10.0-327.36.1.el7.x86_64 #1 SMP Wed Aug 17 03:02:37 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[**_***@clus1master ~]$ 

---

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)

The resource operation completed with terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)

Operation Id 876CAAFC178E2872
Tracking Id 0aaf6dc8-eb34-4bc5-a8d3-e399762e7c58
Status  Conflict
Provisioning State Failed
Timestamp 10/19/2016, 8:16:01 PM
Duration 1 minute 25 seconds
Type Microsoft.Resources/deployments
Resource Id /subscriptions/*******_-**__-_**_-**__-_***********/resourceGroups/OpenShiftRG/providers/Microsoft.Resources/deployments/OpenShiftDeployment
StatusMessage
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{"status": "Failed",  "error": 
                {
                    "code": "ResourceDeploymentFailure",  
                    "message": "The resource operation completed with terminal provisioning state 'Failed'.",  
                    "details": [
                            {
                            "code": "VMExtensionProvisioningError",
                            "message": "VM has reported a failure when processing extension 'deployOpenShift'. 
                            Error message: "Enable failed: failed to execute command: command terminated with exit status=2"."  
                            }
                    ]  
                }
            }"
          }
        ]
      }
    ]
  }
}
Resource OpenShiftDeployment

Parametes as follows

---

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "masterVmSize": {
            "value": "Standard_DS2_v2"
        },
        "nodeVmSize": {
            "value": "Standard_DS2_v2"
        },
        "openshiftClusterPrefix": {
            "value": "clus1"
        },
        "openshiftMasterPublicIpDnsLabel": {
            "value": "mast"
        },
        "nodeLbPublicIpDnsLabel": {
            "value": "nodelb"
        },
        "nodeInstanceCount": {
            "value": 2
        },
        "dataDiskSize": {
            "value": 10
        },
        "adminUsername": {
            "value": "yoterada"
        },
        "openshiftPassword": {
            "value": null
        },
        "cloudAccessUsername": {
            "value": "********@yahoo.co.jp"
        },
        "cloudAccessPassword": {
            "value": null

<img width="646" alt="screensnapz143" src="https://cloud.githubusercontent.com/assets/1871266/19517422/0e4135ac-963c-11e6-8638-11330fef9a7c.png">

**Comment by yoshioterada** [comment]
/var/log/azure/custom-script/handler.log following was wrote.

time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="reading configuration"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="read configuration"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="validating json schema"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="json schema valid"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="parsing configuration json"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="parsed configuration json"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="validating configuration logically"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="validated configuration"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="creating output directory" path=/var/lib/waagent/custom-script/download/1
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="created output directory"
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 files=1
time=2016-10-19T13:08:16Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 file=0 event="download start"
time=2016-10-19T13:08:17Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 file=0 event="download complete" output=/var/lib/waagent/custom-script/download/1
time=2016-10-19T13:08:17Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="executing command" output=/var/lib/waagent/custom-script/download/1
time=2016-10-19T13:08:17Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="failed to execute command" error="command terminated with exit status=2" output=/var/lib/waagent/custom-script/download/1
time=2016-10-19T13:08:17Z version=v2.0.2/git@494f22e-clean operation=enable seq=1 event="failed to handle" error="failed to execute command: command terminated with exit status=2"

**Comment by yoshioterada** [comment]
On following file : /var/lib/waagent/custom-script/download/1/stderr
Following error was showed.
sed: can't read /etc/ansible/ansible.cfg: No such file or directory

So perhaps, there is a bug on deployOpenShift.sh.

---

sed -i -e "s/^# control_path = %(directory)s\/%%h-%%r/control_path = %(directory)s\/%%h-%%r/" /etc/ansible/ansible.cfg
sed -i -e "s/^#host_key_checking = False/host_key_checking = False/" /etc/ansible/ansible.cfg
sed -i -e "s/^#pty=False/pty=False/" /etc/ansible/ansible.cfg

---

**Comment by haroldwongms** [comment]
After troubleshooting with Yoshio, I found two items that contributed to the failure.
1. A passphrase was assigned to the Private Key which will not work since the Ansible Playbook cannot enter the passphrase when executing.
2. The pool ID that was used had no valid subscriptions so none of the repos were able to be enabled and therefore no utilities such as Ansible was installed.

The error / issue is not in the Solution Templates.  I am closing this issue.
