### ISSUE TITLE
Deployments now fails due to failure in DNS resolution

### ISSUE THREAD

**Issue by mglantz** [haroldwongms/openshift-enterprise#3]
I'm not sure why, but now, for me, deployments of non HA clusters (only tried this, guess this issues is for all sorts of deployments though) fails due to DNS resolution issue. When adding the infra and node server names to /etc/hosts, deployOpenShift triggers an successful Ansible run and a cluster is installed properly. Is this something you see as well?

**Comment by mglantz** [comment]
When looking at the masters DNS config, it seems bound to fail.. but this did not happen earlier when I tried, so.. not sure what has changed. Perhaps that it's now running on Red Hat Enterprise Linux 7.3.

```

[root@ocpnnmaster ~]# grep ocpnnnode -r /etc
/etc/ansible/hosts:ocpnnnode-0 openshift_node_labels="{'region': 'nodes', 'zone': 'default'}"

[root@ocpnnmaster ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search mkszgepxlf5ehigwksgcr2qcha.ax.internal.cloudapp.net
nameserver 168.63.129.16

[root@ocpnnmaster ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

[root@ocpnnmaster ~]# ping ocpnnnode-0.mkszgepxlf5ehigwksgcr2qcha.ax.internal.cloudapp.net
ping: ocpnnnode-0.mkszgepxlf5ehigwksgcr2qcha.ax.internal.cloudapp.net: Name or service not known
```

**Comment by mglantz** [comment]
Seems like the IP can be predicted, 192.168.2.4+ will be nodes, and then at the end we'll have the infra node.. but this must have worked before, without hostfile hacks.

**Comment by haroldwongms** [comment]
I have now received numerous emails that the template is failing.  I will look into this and get back to you as this was working fine last month.

**Comment by haroldwongms** [comment]
It seems there is a known issue with DNS resolution on newly deployed RHEL 7.2 / 7.3 images.  The Azure engineering team is working on a resolution for this.  

Until that is corrected, I will not be testing the templates any further at this time.

I am closing this issue for now.

**Comment by mglantz** [comment]
Thanks for the feedback, sounds serious. Hoping for a quick resolution.
